version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "monthly"
  labels:
    - "dependencies"

  ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-major"

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  allow:
    - dependency-name: "github.com/hashicorp/packer-plugin-sdk"
    - dependency-name: "github.com/hashicorp/hcp-sdk-go"
