version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  allow:
    - dependency-name: "github.com/hashicorp/packer-plugin-sdk"
    - dependency-name: "github.com/hashicorp/hcp-sdk-go"
