comment:
  layout: "flags, files"
  behavior: default
  require_changes: true   # only comment on changes in coverage
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "master"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: "0.5%"

ignore:  # ignore hcl2spec generated code for coverage
  - "**/*.hcl2spec.go"