comment:
  layout: "flags, files"
  behavior: default
  require_changes: true   # only comment on changes in coverage
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  after_n_builds: 3       # wait for all OS test coverage builds to post comment
  branches:               # branch names that can post comment
    - "master"

coverage:
  status:
    project: off
    patch: off

ignore:  # ignore hcl2spec generated code for coverage and mocks
  - "**/*.hcl2spec.go"
  - "**/*_mock.go"