package tencent

const (
	CArtifactIPAddress                          string = "IPAddress"
	CArtifactBuilderID                          string = "BuilderID"
	CClientToken                                string = "ClientToken"
	CConfig                                     string = "config"
	CDataDisks_0_DiskSize                       string = "DataDisks.0.DiskSize"
	CDataDisks_0_DiskType                       string = "DataDisks.0.DiskType"
	CDriver                                     string = "driver"
	CEnhancedServiceMonitorServiceEnabled       string = "EnhancedService.MonitorService.Enabled"
	CEnhancedServiceSecurityServiceEnabled      string = "EnhancedService.SecurityService.Enabled"
	CError                                      string = "error"
	CImageId                                    string = "ImageId"
	CImageName                                  string = "ImageName"
	CInstanceChargePrepaidPeriod                string = "InstanceChargePrepaid.Period"
	CInstanceChargePrepaidRenewFlag             string = "InstanceChargePrepaid.RenewFlag"
	CInstanceChargeType                         string = "InstanceChargeType"
	CInstanceCount                              string = "InstanceCount"
	CInstanceId                                 string = "InstanceId"
	CInstanceName                               string = "InstanceName"
	CInstanceType                               string = "InstanceType"
	CInternetAccessible_InternetChargeType      string = "InternetAccessible.InternetChargeType"
	CInternetAccessible_InternetMaxBandwidthOut string = "InternetAccessible.InternetMaxBandwidthOut"
	CInternetAccessible_PublicIpAssigned        string = "InternetAccessible.PublicIpAssigned"
	CKeyName                                    string = "KeyName"
	CLoginSettingsPassword                      string = "LoginSettings.Password"
	CLoginSettingsKeepImageLogin                string = "LoginSettings.KeepImageLogin"
	COBFUSCATED                                 string = "OBFUSCATED"
	CPackerDebug                                string = "PackerDebug"
	CPlacement                                  string = "Placement"
	CPlacementProjectId                         string = "Placement.ProjectId"
	CPlacementZone                              string = "Placement.Zone"
	CProjectId                                  string = "ProjectId"
	CPublicKey                                  string = "PublicKey"
	CRegion                                     string = "Region"
	CSecretId                                   string = "SecretId"
	CSecretKey                                  string = "SecretKey"
	CSSHKeyLocation                             string = "SSHKeyLocation"
	CSSHUserName                                string = "ssh_username"
	CSTOPPED                                    string = "STOPPED"
	CSystemDisk_DiskSize                        string = "SystemDisk.DiskSize"
	CSystemDisk_DiskType                        string = "SystemDisk.DiskType"
	CTimestamp                                  string = "Timestamp"
	CUrl                                        string = "url"
	CVirtualPrivateCloud_AsVpcGateway           string = "VirtualPrivateCloud.AsVpcGateway"
	CVirtualPrivateCloud_VpcId                  string = "VirtualPrivateCloud.VpcId"
	CVirtualPrivateCloud_SubnetId               string = "VirtualPrivateCloud.SubnetId"
	CVersion                                    string = "Version"
	CZone                                       string = "Zone"

	// CVM URL for Silicon Valley and Singpaore
	CCVMUrlSiliconValley string = "cvm.na-siliconvalley.tencentcloudapi.com/"
	CCVMUrlSingapore     string = "cvm.ap-singapore.tencentcloudapi.com/"

	// Image API URL
	CImageAPIUrl string = "image.api.qcloud.com/v2/index.php"

	// constants for steps
	CStepClear             string = "StepClear"
	CStepConnectSSH        string = "StepConnectSSH"
	CStepCreateCustomImage string = "StepCreateCustomImage"
	CStepCreateImage       string = "StepCreateImage"
	CStepCreateKeyPair     string = "StepCreateKeyPair"
	CStepDisplayMessage    string = "StepDisplayMessage"
	CStepGetImageStatus    string = "StepGetImageStatus"
	CStepGetInstanceIP     string = "StepGetInstanceIP"
	CStepGetKeyPairStatus  string = "StepGetKeyPairStatus"
	CStepHalt              string = "StepHalt"
	CStepProvision         string = "StepProvision"
	CStepRunImage          string = "StepRunImage"
	CStepStopImage         string = "StepStopImage"
	CStepWaitRunning       string = "StepWaitRunning"
	CStepWaitStopped       string = "StepWaitStopped"

	CSTEPSTARTING string = "%s starting..."
	CSTEPFINISHED string = "Finished %s successfully"
)
