// Package tmp provides temporary directory helpers.
//
// tmp stores temporary items in the system's
// temporary directory ( see os.TempDir ).
//
// When the $TMPDIR_SUFFIX environment variable
// is set, tmp will return paths under $TMPDIR_SUFFIX
// inside the system temporary directory.
//
package tmp

import (
	"io/ioutil"
	"os"
	"path/filepath"
)

var tmpDir = os.TempDir()

func init() {
	if d := os.Getenv("TMPDIR_SUFFIX"); d != "" {
		tmpDir = filepath.Join(tmpDir, d)
	}
}

// Dir creates a new temporary directory in the system temporary
// directory with a name beginning with prefix and returns the path
// of the new directory.
// Multiple programs calling Dir simultaneously
// will not choose the same directory.
// It is the caller's responsibility
// to remove the file when no longer needed.
func Dir(prefix string) (string, error) {
	return ioutil.TempDir(tmpDir, prefix)
}

// File creates a new temporary file in the system temporary
// directory, opens the file for reading and writing, and
// returns the resulting *os.File.
// The filename is generated by taking pattern and adding a random
// string to the end. If pattern includes a "*", the random string
// replaces the last "*".
// Multiple programs calling File simultaneously
// will not choose the same file. The caller can use f.Name()
// to find the pathname of the file. It is the caller's responsibility
// to remove the file when no longer needed.
func File(pattern string) (*os.File, error) {
	return ioutil.TempFile(tmpDir, pattern)
}
