name: Create a release branch
on: [workflow_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: hashicorp/actions-create-release-branch@v1
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
