name: Create a release branch
on: [workflow_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: hashicorp/actions-create-release-branch@v1
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
