name: Create a release branch
on: [workflow_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: hashicorp/actions-create-release-branch@v1
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
