name: Lint

on: [push, pull_request]

jobs:
  golangci:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: --verbose
